//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ApplicationServices.SdKoersel
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/AnsaettelseKoerselOpret20170501", ConfigurationName="Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType")]
    public interface AnsaettelseKoerselOpret20170501PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws-indberetning/services/AnsaettelseKoerselOpret20170501", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse AnsaettelseKoerselOpret20170501Operation(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws-indberetning/services/AnsaettelseKoerselOpret20170501", ReplyAction="*")]
        System.Threading.Tasks.Task<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse> AnsaettelseKoerselOpret20170501OperationAsync(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01")]
    public partial class AnsaettelseKoerselOpretInputType
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string brugerIdentifikatorField;
        
        private string item1Field;
        
        private Item1ChoiceType item1ElementNameField;
        
        private string registreringTypeIdentifikatorField;
        
        private System.DateTime koerselDatoField;
        
        private decimal kilometerMaalField;
        
        private string kontoNummerIdentifikatorField;
        
        private bool godkendtIndikatorField;
        
        private bool kontrolleretIndikatorField;
        
        private bool dokumentationEksternIndikatorField;
        
        private bool regel60DageIndikatorField;
        
        private string registreringNummerIdentifikatorField;
        
        private string aarsagTekstField;
        
        private string koertFraTekstField;
        
        private string koertTilTekstField;
        
        private string[] koertViaTekstField;
        
        private string item2Field;
        
        private Item2ChoiceType item2ElementNameField;
        
        private string konteringAfvigendeStillingIdentifikatorField;
        
        private string konteringAfvigendeTjenesteKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstitutionIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InstitutionUUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BrugerIdentifikator
        {
            get
            {
                return this.brugerIdentifikatorField;
            }
            set
            {
                this.brugerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnsaettelseIdentifikator", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("AnsaettelseUUIDIdentifikator", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
        public string Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item1ChoiceType Item1ElementName
        {
            get
            {
                return this.item1ElementNameField;
            }
            set
            {
                this.item1ElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=5)]
        public string RegistreringTypeIdentifikator
        {
            get
            {
                return this.registreringTypeIdentifikatorField;
            }
            set
            {
                this.registreringTypeIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", DataType="date", Order=6)]
        public System.DateTime KoerselDato
        {
            get
            {
                return this.koerselDatoField;
            }
            set
            {
                this.koerselDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=7)]
        public decimal KilometerMaal
        {
            get
            {
                return this.kilometerMaalField;
            }
            set
            {
                this.kilometerMaalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KontoNummerIdentifikator
        {
            get
            {
                return this.kontoNummerIdentifikatorField;
            }
            set
            {
                this.kontoNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool GodkendtIndikator
        {
            get
            {
                return this.godkendtIndikatorField;
            }
            set
            {
                this.godkendtIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool KontrolleretIndikator
        {
            get
            {
                return this.kontrolleretIndikatorField;
            }
            set
            {
                this.kontrolleretIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool DokumentationEksternIndikator
        {
            get
            {
                return this.dokumentationEksternIndikatorField;
            }
            set
            {
                this.dokumentationEksternIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=12)]
        public bool Regel60DageIndikator
        {
            get
            {
                return this.regel60DageIndikatorField;
            }
            set
            {
                this.regel60DageIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/registreringnummer/xml/schemas/20080401/", Order=13)]
        public string RegistreringNummerIdentifikator
        {
            get
            {
                return this.registreringNummerIdentifikatorField;
            }
            set
            {
                this.registreringNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=14)]
        public string AarsagTekst
        {
            get
            {
                return this.aarsagTekstField;
            }
            set
            {
                this.aarsagTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=15)]
        public string KoertFraTekst
        {
            get
            {
                return this.koertFraTekstField;
            }
            set
            {
                this.koertFraTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=16)]
        public string KoertTilTekst
        {
            get
            {
                return this.koertTilTekstField;
            }
            set
            {
                this.koertTilTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KoertViaTekst", Order=17)]
        public string[] KoertViaTekst
        {
            get
            {
                return this.koertViaTekstField;
            }
            set
            {
                this.koertViaTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KonteringAfvigendeEnhedIdentifikator", typeof(string), Order=18)]
        [System.Xml.Serialization.XmlElementAttribute("KonteringAfvigendeEnhedUUIDIdentifikator", typeof(string), Order=18)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item2ElementName")]
        public string Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item2ChoiceType Item2ElementName
        {
            get
            {
                return this.item2ElementNameField;
            }
            set
            {
                this.item2ElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string KonteringAfvigendeStillingIdentifikator
        {
            get
            {
                return this.konteringAfvigendeStillingIdentifikatorField;
            }
            set
            {
                this.konteringAfvigendeStillingIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string KonteringAfvigendeTjenesteKode
        {
            get
            {
                return this.konteringAfvigendeTjenesteKodeField;
            }
            set
            {
                this.konteringAfvigendeTjenesteKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        InstitutionIdentifikator,
        
        /// <remarks/>
        InstitutionUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum Item1ChoiceType
    {
        
        /// <remarks/>
        AnsaettelseIdentifikator,
        
        /// <remarks/>
        AnsaettelseUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum Item2ChoiceType
    {
        
        /// <remarks/>
        KonteringAfvigendeEnhedIdentifikator,
        
        /// <remarks/>
        KonteringAfvigendeEnhedUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01")]
    public partial class AnsaettelseKoerselOpret20170501Type
    {
        
        private AnsaettelseKoerselOpretInputType inddataStrukturField;
        
        private string registreringIdentifikatorField;
        
        private System.DateTime dannetDatoTidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AnsaettelseKoerselOpretInputType InddataStruktur
        {
            get
            {
                return this.inddataStrukturField;
            }
            set
            {
                this.inddataStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegistreringIdentifikator
        {
            get
            {
                return this.registreringIdentifikatorField;
            }
            set
            {
                this.registreringIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dannetDatoTid
        {
            get
            {
                return this.dannetDatoTidField;
            }
            set
            {
                this.dannetDatoTidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsaettelseKoerselOpret20170501OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", Order=0)]
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret;
        
        public AnsaettelseKoerselOpret20170501OperationRequest()
        {
        }
        
        public AnsaettelseKoerselOpret20170501OperationRequest(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret)
        {
            this.AnsaettelseKoerselOpret = AnsaettelseKoerselOpret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsaettelseKoerselOpret20170501OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", Order=0)]
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501Type AnsaettelseKoerselOpret20170501;
        
        public AnsaettelseKoerselOpret20170501OperationResponse()
        {
        }
        
        public AnsaettelseKoerselOpret20170501OperationResponse(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501Type AnsaettelseKoerselOpret20170501)
        {
            this.AnsaettelseKoerselOpret20170501 = AnsaettelseKoerselOpret20170501;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface AnsaettelseKoerselOpret20170501PortTypeChannel : Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class AnsaettelseKoerselOpret20170501PortTypeClient : System.ServiceModel.ClientBase<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType>, Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AnsaettelseKoerselOpret20170501PortTypeClient() : 
                base(AnsaettelseKoerselOpret20170501PortTypeClient.GetDefaultBinding(), AnsaettelseKoerselOpret20170501PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AnsaettelseKoerselOpret20170501.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(AnsaettelseKoerselOpret20170501PortTypeClient.GetBindingForEndpoint(endpointConfiguration), AnsaettelseKoerselOpret20170501PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AnsaettelseKoerselOpret20170501PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AnsaettelseKoerselOpret20170501PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse AnsaettelseKoerselOpret20170501Operation(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request)
        {
            return base.Channel.AnsaettelseKoerselOpret20170501Operation(request);
        }
        
        public System.Threading.Tasks.Task<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse> AnsaettelseKoerselOpret20170501OperationAsync(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request)
        {
            return base.Channel.AnsaettelseKoerselOpret20170501OperationAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AnsaettelseKoerselOpret20170501))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AnsaettelseKoerselOpret20170501))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws-indberetning/services/AnsaettelseKoerselOpret20170501");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AnsaettelseKoerselOpret20170501PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AnsaettelseKoerselOpret20170501);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AnsaettelseKoerselOpret20170501PortTypeClient.GetEndpointAddress(EndpointConfiguration.AnsaettelseKoerselOpret20170501);
        }
        
        public enum EndpointConfiguration
        {
            
            AnsaettelseKoerselOpret20170501,
        }
    }
}
