//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ApplicationServices.SDService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/KoerselOpret20120201", ConfigurationName="Core.ApplicationServices.SDService.KoerselOpret20120201PortType")]
    public interface KoerselOpret20120201PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/KoerselOpret20120201", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Core.ApplicationServices.SDService.KoerselOpret20120201OperationResponse KoerselOpret20120201Operation(Core.ApplicationServices.SDService.KoerselOpret20120201OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/KoerselOpret20120201", ReplyAction="*")]
        System.Threading.Tasks.Task<Core.ApplicationServices.SDService.KoerselOpret20120201OperationResponse> KoerselOpret20120201OperationAsync(Core.ApplicationServices.SDService.KoerselOpret20120201OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01")]
    public partial class KoerselOpretRequestType
    {
        
        private string institutionIdentifikatorField;
        
        private string personnummerIdentifikatorField;
        
        private string ansaettelseIdentifikatorField;
        
        private string registreringTypeIdentifikatorField;
        
        private System.DateTime koerselDatoField;
        
        private decimal kilometerMaalField;
        
        private bool regel60DageIndikatorField;
        
        private string koertFraTekstField;
        
        private string koertTilTekstField;
        
        private string aarsagTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionIdentifikator
        {
            get
            {
                return this.institutionIdentifikatorField;
            }
            set
            {
                this.institutionIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PersonnummerIdentifikator
        {
            get
            {
                return this.personnummerIdentifikatorField;
            }
            set
            {
                this.personnummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnsaettelseIdentifikator
        {
            get
            {
                return this.ansaettelseIdentifikatorField;
            }
            set
            {
                this.ansaettelseIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegistreringTypeIdentifikator
        {
            get
            {
                return this.registreringTypeIdentifikatorField;
            }
            set
            {
                this.registreringTypeIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime KoerselDato
        {
            get
            {
                return this.koerselDatoField;
            }
            set
            {
                this.koerselDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal KilometerMaal
        {
            get
            {
                return this.kilometerMaalField;
            }
            set
            {
                this.kilometerMaalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Regel60DageIndikator
        {
            get
            {
                return this.regel60DageIndikatorField;
            }
            set
            {
                this.regel60DageIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string KoertFraTekst
        {
            get
            {
                return this.koertFraTekstField;
            }
            set
            {
                this.koertFraTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KoertTilTekst
        {
            get
            {
                return this.koertTilTekstField;
            }
            set
            {
                this.koertTilTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AarsagTekst
        {
            get
            {
                return this.aarsagTekstField;
            }
            set
            {
                this.aarsagTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01")]
    public partial class KoerselOpret20120201Type
    {
        
        private KoerselOpretRequestType inddataStrukturField;
        
        private System.DateTime dannetDatoTidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KoerselOpretRequestType InddataStruktur
        {
            get
            {
                return this.inddataStrukturField;
            }
            set
            {
                this.inddataStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dannetDatoTid
        {
            get
            {
                return this.dannetDatoTidField;
            }
            set
            {
                this.dannetDatoTidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KoerselOpret20120201OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=0)]
        public Core.ApplicationServices.SDService.KoerselOpretRequestType InddataStruktur;
        
        public KoerselOpret20120201OperationRequest()
        {
        }
        
        public KoerselOpret20120201OperationRequest(Core.ApplicationServices.SDService.KoerselOpretRequestType InddataStruktur)
        {
            this.InddataStruktur = InddataStruktur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KoerselOpret20120201OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=0)]
        public Core.ApplicationServices.SDService.KoerselOpret20120201Type KoerselOpret20120201;
        
        public KoerselOpret20120201OperationResponse()
        {
        }
        
        public KoerselOpret20120201OperationResponse(Core.ApplicationServices.SDService.KoerselOpret20120201Type KoerselOpret20120201)
        {
            this.KoerselOpret20120201 = KoerselOpret20120201;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface KoerselOpret20120201PortTypeChannel : Core.ApplicationServices.SDService.KoerselOpret20120201PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class KoerselOpret20120201PortTypeClient : System.ServiceModel.ClientBase<Core.ApplicationServices.SDService.KoerselOpret20120201PortType>, Core.ApplicationServices.SDService.KoerselOpret20120201PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KoerselOpret20120201PortTypeClient() : 
                base(KoerselOpret20120201PortTypeClient.GetDefaultBinding(), KoerselOpret20120201PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.KoerselOpret20120201.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KoerselOpret20120201PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(KoerselOpret20120201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), KoerselOpret20120201PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KoerselOpret20120201PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KoerselOpret20120201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KoerselOpret20120201PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KoerselOpret20120201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KoerselOpret20120201PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Core.ApplicationServices.SDService.KoerselOpret20120201OperationResponse KoerselOpret20120201Operation(Core.ApplicationServices.SDService.KoerselOpret20120201OperationRequest request)
        {
            return base.Channel.KoerselOpret20120201Operation(request);
        }
        
        public System.Threading.Tasks.Task<Core.ApplicationServices.SDService.KoerselOpret20120201OperationResponse> KoerselOpret20120201OperationAsync(Core.ApplicationServices.SDService.KoerselOpret20120201OperationRequest request)
        {
            return base.Channel.KoerselOpret20120201OperationAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KoerselOpret20120201))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KoerselOpret20120201))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws/services/KoerselOpret20120201");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KoerselOpret20120201PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.KoerselOpret20120201);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KoerselOpret20120201PortTypeClient.GetEndpointAddress(EndpointConfiguration.KoerselOpret20120201);
        }
        
        public enum EndpointConfiguration
        {
            
            KoerselOpret20120201,
        }
    }
}
